apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: servicesautomation-master-default-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       servicesautomation-master-default
  updatePolicy:
    updateMode: "Auto"
