

apiVersion: v1
kind: Service
metadata:
  name: servicesautomation-master-default
  labels:
    app: servicesautomation-master-default
spec:
  ports:
  - name: port80
    port: 80
  selector:
    app: servicesautomation-master-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicesautomation-master-default
  labels:
    app: servicesautomation-master-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicesautomation-master-default
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: servicesautomation-master-default
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        type: Standard
      containers:
      - name: servicesautomation-master-default
        imagePullPolicy: Always
        image: ploomes.azurecr.io/ploomes/servicesautomation:master-development
        ports:
        - containerPort: 80
        
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: servicesautomation-master-default-environment-variables
              key: ASPNETCORE_ENVIRONMENT
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: servicesautomation-master-default-secrets
